[package]
name = "learnnet"
version = "0.1.0"
authors = ["stevenpack <steven.pack.code@gmail.com>"]

[dependencies]
rocket = "0.3.3"
rocket_codegen = "0.3.3"
chrono = "0.4"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"